## 
##humboldt do it all

humboldt.doitall(inname = "DoItAll",
                 env1= env1, 
                 env2= env2, 
                 sp1 = occ.sp1,
                 sp2= occ.sp2,
                 rarefy.dist = 0.5, 
                 rarefy.units = "km", 
                 env.reso = 0.00833, 
                 reduce.env = 2,
                 reductype = "PCA", 
                 non.analogous.environments = "YES",
                 nae.window = 5,
                 env.trim = T, 
                 env.trim.type = "MCP", 
                 #trim.mask1,
                 #trim.mask2, 
                 trim.buffer.sp1 = 5, 
                 trim.buffer.sp2 = 5,
                 color.ramp = 1, 
                 correct.env = T, 
                 pcx = 1, 
                 pcy = 2,
                 col.env = e.var,
                 e.var=(3:25), 
                 R = 500, 
                 kern.smooth = 0.5, 
                 e.reps = 100,
                 b.reps = 100, 
                 b.force.equal.sample = F, 
                 nae = "YES",
                 thresh.espace.z = 0.001, 
                 p.overlap = T, 
                 p.boxplot = T,
                 p.scatter = T, 
                 run.silent = T, 
                 ncores = 1)
